services:
  - type: web
    name: django-tutorials-staticproject
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn staticProject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: staticProject.settings
